name: Format Code
on:
  - push

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up pnpm
        uses: pnpm/action-setup@master
        with:
          version: latest
          cache: true

      - name: Install dependencies
        run: pnpm i

      - name: Run formatter
        run: pnpm format:check
